RATING_MERGE_DICT = {
    'mixture': 'false',
    'mostly false': 'false',
    'pants on fire': 'false',
    'mostly true': 'true',
    'misleading': 'false',
    'altered': 'false',
    'four pinocchios': 'false',
    'inaccurate': 'false',
    'distorts the facts': 'false',
    'incorrect': 'false',
    'three pinocchios': 'false',
    'half true': 'false',
    'partly false': 'false',
    'correct.': 'true',
    'correct': 'true',
    'incorrect.': 'false',
    'true.': 'true',
    'false.': 'false',
    'wrong': 'false',
    'this is misleading': 'false',
    'pants on fire!': 'false',
    'mostly_accurate': 'true',
    'this is accurate': 'true',
    'this is not true.': 'false',
    'mis- leading': 'false',
    'partially_correct': 'false',
    'spins the facts': 'false',
    'spinning the facts': 'false',
    'twists the facts': 'false',
    'largely correct': 'true',
    'not true': 'false',
    'not true.': 'false',
    'one pinocchio': 'false',
    'two pinocchios': 'false',
    'this is wrong': 'false',
    'this is correct.': 'true',
    'partly true': 'false',
    'accurate': 'true',
    'not accurate': 'false',
    'not the whole story': 'false',
    'mostly accurate': 'true',
    'unproven': 'false',
    'unsupported': 'false',
    'no evidence': 'false',
    'unfounded': 'false',
    'this is misleading': 'false',
    'false: no evidence': 'false',
    'lacks evidence': 'false',
    'largely accurate': 'true',
    'misleading.': 'false',
    'there is no evidence for this.': 'false',
    'this is misleading.': 'false',
    'not proven': 'false',
    'mostly_correct': 'true',
    'that’s correct.': 'true',
}